controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    
   # Publish all joint states -----------------------------------
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Position Controllers ---------------------------------------
    # uthai_controller:
    #   type: position_controllers/JointGroupPositionController

    # Left Leg -----
    l_hip_yaw_position:
      type: joint_trajectory_controller/JointTrajectoryController
      

    l_hip_roll_position:
      type: joint_trajectory_controller/JointTrajectoryController

    l_hip_pitch_position:
      type: joint_trajectory_controller/JointTrajectoryController

    l_knee_pitch_position:
      type: joint_trajectory_controller/JointTrajectoryController


    l_ankle_pitch_position:
      type: joint_trajectory_controller/JointTrajectoryController


    l_ankle_roll_position:
      type: joint_trajectory_controller/JointTrajectoryController

    # Right Leg -----

    r_hip_yaw_position:
      type: joint_trajectory_controller/JointTrajectoryController
      
    r_hip_roll_position:
      type: joint_trajectory_controller/JointTrajectoryController
      

    r_hip_pitch_position:
      type: joint_trajectory_controller/JointTrajectoryController
      
    r_knee_pitch_position:
      type: joint_trajectory_controller/JointTrajectoryController
      
    r_ankle_pitch_position:
      type: joint_trajectory_controller/JointTrajectoryController
      

    r_ankle_roll_position:
      type: joint_trajectory_controller/JointTrajectoryController

# command_interfaces:
#       
# state_interfaces:
#   - position
#   - velocity
#   
# Left Leg -----
l_hip_yaw_position:
  ros__parameters:
    joints: 
      - l_hip_yaw_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}
    interface_name: position
    state_publish_rate: 1000.0
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      

l_hip_roll_position:
  ros__parameters:
    joints: 
      - l_hip_roll_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}
    interface_name: position
    state_publish_rate: 1000.0
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      


l_hip_pitch_position:
  ros__parameters:
    joints: 
      - l_hip_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}
    interface_name: position
    state_publish_rate: 1000.0
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      
    

l_knee_pitch_position:
  ros__parameters:
    joints: 
      - l_knee_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}
    interface_name: position
    state_publish_rate: 1000.0
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      
    

l_ankle_pitch_position:
  ros__parameters:
    joints: 
      - l_ankle_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}
    interface_name: position
    state_publish_rate: 1000.0
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      
    

l_ankle_roll_position:
  ros__parameters:
    joints: 
      - l_ankle_roll_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}
    interface_name: position
    state_publish_rate: 1000.0
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      
    

# Right Leg -----

r_hip_yaw_position:
  ros__parameters:
    joints: 
      - r_hip_yaw_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}
    interface_name: position
    state_publish_rate: 1000.0
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      
    

r_hip_roll_position:
  ros__parameters:
    joints: 
      - r_hip_roll_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}
    interface_name: position
    state_publish_rate: 1000.0
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      
    

r_hip_pitch_position:
  ros__parameters:
    joints: 
      - r_hip_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}
    interface_name: position
    state_publish_rate: 1000.0
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      
    

r_knee_pitch_position:
  ros__parameters:
    joints: 
      - r_knee_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}
    interface_name: position
    state_publish_rate: 1000.0
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      
    

r_ankle_pitch_position:
  ros__parameters:
    joints: 
      - r_ankle_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}
    interface_name: position
    state_publish_rate: 1000.0
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      
    

r_ankle_roll_position:
  ros__parameters:
    joints: 
      - r_ankle_roll_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}
    interface_name: position
    state_publish_rate: 1000.0
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      

# uthai_controller:
#   ros__parameters:
#     joints:
#       - l_hip_yaw_joint
#       - l_hip_roll_joint
#       - l_hip_pitch_joint
#       - l_knee_pitch_joint
#       - l_ankle_roll_joint
#       - l_ankle_pitch_joint
#       - r_hip_yaw_joint
#       - r_hip_roll_joint
#       - r_hip_pitch_joint
#       - r_knee_pitch_joint
#       - r_ankle_roll_joint
#       - r_ankle_pitch_joint
      
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
#       
    